version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./config/:/mosquitto/config/:rw
      - ./log/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
  listener:
    image: ghcr.io/energy-abacus/mqttlistener:main
    environment:
      - mosquitto_ip=mosquitto
      - mosquitto_port=1883
    env_file:
      - abacus_config
volumes:
  data: 
